[package]
name = "devctrl"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
scc = "2.2.5"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
tokio = { version = "1.42.0", features = ["full"] }
schemars = "0.8.21"